# Generated by Django 5.1.2 on 2024-11-01 12:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='call_to_action',
            field=models.CharField(default='', max_length=255, verbose_name='Call to Action'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_title',
            field=models.CharField(default='', max_length=255, verbose_name='Main Title'),
        ),
    ]
