# Generated by Django 5.1.2 on 2024-11-02 19:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_call_to_action_homepage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'required': True, 'verbose_name': 'Service Title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True, 'verbose_name': 'Service Description'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False, 'verbose_name': 'Service Image'}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}, verbose_name='Services'),
        ),
    ]
