# Generated by Django 5.1.2 on 2024-11-09 15:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us_images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'About Us Image', 'required': False})}, verbose_name='About Us Images'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_us_subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='About Us Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_us_title',
            field=models.CharField(default='', max_length=255, verbose_name='About Us Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='additional_services_subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Additional Service Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='additional_services_text',
            field=wagtail.fields.RichTextField(default='', verbose_name='Additional Service Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='additional_services_title',
            field=models.CharField(default='', max_length=255, verbose_name='Additional Services Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_links',
            field=wagtail.fields.StreamField([('link', 1)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'required': True, 'verbose_name': 'Link Text'}), 1: ('wagtail.blocks.StructBlock', [[('link_text', 0)]], {})}, verbose_name='Footer Links'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=wagtail.fields.RichTextField(default='', verbose_name='Footer Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Gallery Image', 'required': False})}, verbose_name='Gallery Images'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_title',
            field=models.CharField(default='', max_length=255, verbose_name='Gallery Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone_number_1',
            field=models.CharField(default='', max_length=255, verbose_name='Phone Number 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone_number_2',
            field=models.CharField(default='', max_length=255, verbose_name='Phone Number 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_footer_note',
            field=models.CharField(default='', max_length=255, verbose_name='Services Footer Note'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_section_description',
            field=wagtail.fields.RichTextField(default='', verbose_name='Services Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_section_title',
            field=models.CharField(default='', max_length=255, verbose_name='Services Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='timeline_date',
            field=models.CharField(default='', max_length=255, verbose_name='About Us Timeline Date'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='timeline_description',
            field=wagtail.fields.RichTextField(default='', verbose_name='About Us Timeline Description'),
        ),
    ]
