# Generated by Django 5.1.2 on 2024-11-09 15:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_about_us_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us_subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='About Us Subtitle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_us_stories',
            field=wagtail.fields.StreamField([('story', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True, 'verbose_name': 'Timeline Date'}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True, 'verbose_name': 'Story Text'}), 2: ('wagtail.blocks.StructBlock', [[('timeline_date', 0), ('story_text', 1)]], {'verbose_name': 'Story'})}, verbose_name='About Us Stories'),
        ),
    ]
